name: CodeClimate-Checks
on:
  push:
    branches-ignore:
      - 'test'
  workflow_dispatch:

jobs:
  
  collect-backend-coverage:
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '5.0'

      - name: Install Coverage
        run: |
          pip install coverage
        
      - uses: amancevice/setup-code-climate@v0
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
          cc_test_reporter_version: latest  # optional

      - run: cc-test-reporter before-build

      - name: Generate coverage report
        run: |
          coverage run -m unittest test_pytest.py

      - name: Run report generator
        run: |
          coverage report -m

      - name: Collect Backend Report
        run: |
          cc-test-reporter upload-coverage -t lcov -o backend.json .coverage -p 

      # - name: Create backend coverage file artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: backend
      #     path: ./prime-dotnet-webapi-tests/coverage/backend.json
      #     retention-days: 1
          

  # codeclimate-sum-coverage:
  #   needs: [ collect-frontend-coverage, collect-backend-coverage ]

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: amancevice/setup-code-climate@v0
  #       with:
  #         cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
  #         cc_test_reporter_version: latest  # optional

  #     - name: Download frontend artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: frontend
  #         # path: frontend/

  #     - name: Download backend artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: backend
  #         # path: backend/

  #     - name: Sum files
  #       run: |          
  #         cc-test-reporter sum-coverage -p 2 frontend.json backend.json
  #         cc-test-reporter upload-coverage -i ./coverage/codeclimate.json
      
  #     - name: Create summed report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: summed
  #         path: ./coverage/codeclimate.json
  #         retention-days: 1
